module AllTests where

import AutoLambdaCaseInBind
import AutoLambdaCaseInCase
import BangPatterns
import CanonicalInstance
import Coerce
import Coinduction
import CommonQualifiedImports
import ConstrainedInstance
import Datatypes
import Default
import DefaultMethods
import Delay
import Deriving
import DoNotation
import EraseType
import ErasedLocalDefinitions
import ErasedTypeArguments
import Fixities
import HeightMirror
import IOFile
import IOInput
import Importer
import Inlining
import Issue115
import Issue14
import Issue145
import Issue169
import Issue200
import Issue210
import Issue218
import Issue251
import Issue264
import Issue273
import Issue286
import Issue301
import Issue302
import Issue305
import Issue65
import Issue69
import Issue73
import Issue90
import Issue92
import Issue93
import Issue94
import Kinds
import LanguageConstructs
import LawfulOrd
import LiteralPatterns
import ModuleParameters
import ModuleParametersImports
import NewTypePragma
import NonClassInstance
import Numbers
import Pragmas
import ProjLike
import QualifiedImports
import QualifiedModule
import QualifiedPrelude
import Records
import RequalifiedImports
import ScopedTypeVariables
import Sections
import Superclass
import Test
import TransparentFun
import Tree
import Tuples
import TypeBasedUnboxing
import TypeDirected
import TypeOperatorExport
import TypeOperatorImport
import TypeOperators
import TypeSignature
import TypeSynonyms
import UnboxPragma
import Vector
import Where
import WitnessedFlows
